#spring:
#  jpa:
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#
#    defer-datasource-initialization: true
#
#  datasource:
#    url: jdbc:h2:mem:testdb
#    username: sa
#
#  h2:
#    console:
#      enabled: true

spring:
  jpa:
    database: mysql
    hibernate.ddl-auto: update
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: root
    password: ${SPRING_DATASOURCE_PASSWORD}

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 106453341605-64801ronf4qmpbaeebfl925ftshptlh9.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

jwt:
  issuer: kmymy27@gmail.com
  # 특정값을 Base64로 인코딩한 값
  secret_key: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK